# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_arm
  joint_model_group_pose: upright_left
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_arm_Art1_Yaw
    - left_arm_Art2_Pitch
    - left_arm_Art3_Pitch
    - left_arm_Art4_Yaw
    - left_arm_Art5_Pitch
    - left_arm_Art6_Yaw
    - left_arm_finger1_prismatic
    - left_arm_finger2_prismatic
    - right_arm_Art1_Yaw
    - right_arm_Art2_Pitch
    - right_arm_Art3_Pitch
    - right_arm_Art4_Yaw
    - right_arm_Art5_Pitch
    - right_arm_Art6_Yaw
    - right_arm_finger1_prismatic
    - right_arm_finger2_prismatic
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - left_arm_Art1_Yaw
      - left_arm_Art2_Pitch
      - left_arm_Art3_Pitch
      - left_arm_Art4_Yaw
      - left_arm_Art5_Pitch
      - left_arm_Art6_Yaw
  - name: left_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - left_arm_finger1_prismatic
      - left_arm_finger2_prismatic
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_arm_Art1_Yaw
      - right_arm_Art2_Pitch
      - right_arm_Art3_Pitch
      - right_arm_Art4_Yaw
      - right_arm_Art5_Pitch
      - right_arm_Art6_Yaw
  - name: right_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_arm_finger1_prismatic
      - right_arm_finger2_prismatic