#Service message to control an arm to a position in the xyz space
float32 x
float32 y
float32 z 
float32 vel #Between 1 and 0. Use 1 for max velocity
string named_pose #Use to override position and go to a named pose. E.g., "home"
---
bool plan #Planning success
bool execute #Execution success

