#ros_parameters_oscar.yaml: Configures ROS topics for the MDB experiment.
#Author: Grupo Integrado de Ingenieria
#Modified: Emanuel Fallas
#Distributed under GPLv3


# Topic to publish reward
/mdb/reward_topic: /mdb/reward
/mdb/reward_msg: std_msgs.msg.Float64
# Topic to send commands from one node to another
/mdb/control_topic: /mdb/oscar/control
/mdb/control_msg: mdb_common.msg.ControlMsg
# Topic to publish information about the current state of an experiment
/mdb/info_topic: /mdb/ltm/info
/mdb/info_msg: mdb_common.msg.InfoMsg
# Topic to publish Perception creation
/mdb/perception_topic: /mdb/ltm/perception
/mdb/perception_msg: mdb_common.msg.NodeMsg
# Topic to publish P-node creation
/mdb/p_node_topic: /mdb/ltm/p_node
/mdb/p_node_msg: mdb_common.msg.PNodeMsg
# Topic to publish P-node updates
/mdb/p_node_update_topic: /mdb/ltm/p_node_update
/mdb/p_node_update_msg: mdb_common.msg.PointMsg
# Topic to publish C-node creation
/mdb/c_node_topic: /mdb/ltm/c_node
/mdb/c_node_msg: mdb_common.msg.NodeMsg
# Topic to publish Goal creation
/mdb/goal_topic: /mdb/motiven/goal
/mdb/goal_msg: mdb_common.msg.NodeMsg
# Topic to publish goal activations
/mdb/goal_activation_topic: /mdb/motiven/goal_activation
/mdb/goal_activation_msg: mdb_common.msg.GoalActivationMsg
# Topic to publish goal accomplishment
/mdb/goal_ok_topic: /mdb/motiven/goal_ok
/mdb/goal_ok_msg: mdb_common.msg.GoalOkMsg
# Topic to publish Forward Model creation
/mdb/forward_model_topic: /mdb/stm/forward_model
/mdb/forward_model_msg: mdb_common.msg.NodeMsg
# Topic to publish Policy creation
/mdb/policy_topic: /mdb/stm/policy
/mdb/policy_msg: mdb_common.msg.NodeMsg
# Topic to publish the executed policy's id
/mdb/executed_policy_topic: /mdb/ltm/executed_policy
/mdb/executed_policy_msg: std_msgs.msg.String
#Topics for OSCAR's sensors
/mdb/oscar/sensor/red_object_topic: /mdb/oscar/sensor/red_object
/mdb/oscar/sensor/red_object_msg: mdb_common.msg.ObjectListMsg
/mdb/oscar/sensor/basket_topic: /mdb/oscar/sensor/basket
/mdb/oscar/sensor/basket_msg: mdb_common.msg.ObjectListMsg
/mdb/oscar/sensor/oscar_in_left_hand_topic: /mdb/oscar/sensor/oscar_in_left_hand
/mdb/oscar/sensor/oscar_in_left_hand_msg: std_msgs.msg.Bool
/mdb/oscar/sensor/oscar_in_right_hand_topic: /mdb/oscar/sensor/oscar_in_right_hand
/mdb/oscar/sensor/oscar_in_right_hand_msg: std_msgs.msg.Bool

